apiVersion: v1
kind: Service
metadata:
  name: notesapp-backend-service
spec:
  selector:
    app: notesapp-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP