apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notesapp-frontend
  template:
    metadata:
      labels:
        app: notesapp-frontend
    spec:
      containers:
        - name: frontend
          image: pam2002/notesapp-frontend:latest
          ports:
            - containerPort: 3000